version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - 'mantainers'

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers: 
      - 'mantainers'
      
