---
name: Check TF Validate

on: ['workflow_call']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  check-tf-validate:
    name: Check TF Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache TF Modules
        id: cache_modules
        uses: actions/cache@v4.1.0
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-tf-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-tf-${{ github.sha }}

      - name: Run TF Validate
        id: check_validate
        run: terraform validate
