---
name: Check TF Format

on: ['workflow_call']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  check-tf-format:
    name: Check TF Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check TF Formatting
        id: tf_fmt
        run: terraform fmt -recursive -diff -check -write=false
