---
name: Checkov Status

run-name: "#${{ github.event.client_payload.id }}: ${{ github.event.client_payload.ref }}"

on:
  workflow_call:
  repository_dispatch:
    types: ['checks']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  checkov-status:
    name: Checkov Status
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.client_payload.ref }}

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12.2884.0
        with:
          directory: .
          quiet: true
          soft_fail: false
          framework: terraform
          output_format: github_failed_only
          download_external_modules: true
          log_level: WARNING
          container_user: 1000
