---
name: Check TF README

run-name: "#${{ github.event.client_payload.id }}: ${{ github.event.client_payload.ref }}"

on:
  workflow_call:
  repository_dispatch:
    types: ['checks']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  check-tf-readme:
    name: Check TF README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.client_payload.ref }}

      - name: Run TF Docs
        id: check_docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: ".terraform-docs.yml"
          git-push: false
          fail-on-diff: true
          output-format: ""
          output-method: "replace"
          output-file: "README.md"
          template: ""
