---
name: Updates and Checks

on: ['push', 'workflow_call']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/tf-init.yaml

  updates:
    if: ${{ github.ref_name != github.event.repository.default_branch }}
  
    name: Updates
    needs: ['setup']
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Updates
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: context.job,
              client_payload: {
                id: context.runId
                "sha": context.sha,
                "ref": context.ref
              }
            });

  checks:
    if: ${{ Always() }}
    
    name: Checks
    needs: ['setup', 'updates']
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Checks
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: context.job,
              client_payload: {
                id: context.runId
                "sha": context.sha,
                "ref": context.ref
              }
            });
