---
name: Updates and Checks

on: ['push', 'workflow_call']

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/tf-init.yaml

  updates:
    name: Updates
    if: ${{ always() && github.ref_name != github.event.repository.default_branch }}
    uses: ./.github/workflows/updates.yaml
    needs: ['setup']

  checks:
    name: Checks
    if: ${{ Always() }}
    uses: ./.github/workflows/checks.yaml
    needs: ['setup', 'updates']
