---
name: Updates and Checks

on: ['push', 'workflow_call']

permissions:
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "setup",
              client_payload: {
                details: {
                  id: "${{ github.sha }}",
                  status: "success",
                  timestamp: "${{ github.event.timestamp }}"
                }
              }
            });

  updates:
    name: Updates
    if: ${{ always() && github.ref_name != github.event.repository.default_branch }}
    uses: ./.github/workflows/updates.yaml
    needs: ['setup']

  checks:
    name: Checks
    if: ${{ Always() }}
    uses: ./.github/workflows/checks.yaml
    needs: ['setup', 'updates']
