---
name: Updates and Checks

on: ['push', 'workflow_call']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/tf-init.yaml

  updates:
    name: Updates
    needs: ['setup']
    runs-on: ubuntu-latest

    if: ${{ github.ref_name != github.event.repository.default_branch }}

    steps:
      - name: Trigger Updates
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "updates",
              client_payload: {
                id: "${{ github.sha }}",
              }
            });

  checks:
    name: Checks
    needs: ['setup', 'updates']
    runs-on: ubuntu-latest

    if: ${{ Always() }}

    steps:
      - name: Trigger Checks
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "checks",
              client_payload: {
                id: "${{ github.sha }}"
              }
            });
