---
name: Updates and Checks

on: ['push', 'workflow_call']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "setup",
              client_payload: {
                details: {
                  id: "${{ github.sha }}",
                  status: "success",
                  timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
                }
              }
            });

  updates:
    if: ${{ github.ref_name != github.event.repository.default_branch }}

    name: Updates
    needs: ['setup']
    runs-on: ubuntu-latest

    steps:
      - name: Updates
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "updates",
              client_payload: {
                details: {
                  id: "${{ github.sha }}",
                  status: "success",
                  timestamp: "${{ github.event.timestamp }}"
                }
              }
            });

  checks:
    name: Checks
    needs: ['setup', 'updates']
    runs-on: ubuntu-latest

    if: ${{ Always() }}

    steps:
      - name: Trigger Checks
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "checks",
              client_payload: {
                details: {
                  id: "${{ github.sha }}",
                  status: "success",
                  timestamp: "${{ github.event.timestamp }}"
                }
              }
            });
