---
name: Terraform Docs Update Auto Run

on:
  push:
    branches-ignore: [ 'main' ]
    
permissions: 
  contents: write
  
jobs:
  readme-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3          
          
      - name: Terraform Init
        run:  terraform init -backend=false

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Create Git Branch
        run: |
          git config user.name "${{github.workflow}}"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git commit -am "AUTO format files"    

      - name: terraform-docs-gh-actions
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: .terraform-docs.yml
          working-dir: .
          git-push: true
          git-commit-message: "AUTO update README"
          git-push-sign-off: true
