---
name: Check/Update Docs, Formatting and Dependencies

on: ['push']

permissions: 
  contents: write
  
jobs:
  terraform-init:
    name: Terraform Init
    runs-on: ubuntu-latest
    
    steps:       
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Terraform Init
        id: terraform_init
        shell: bash
        run:  terraform init -backend=false -input=false -upgrade
        
      - name: Cache Terraform Modules
        id: cache_modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

  terraform-docs-deps-update:
    if: ${{ github.event_name == 'push' && github.ref_name != github.event.repository.default_branch }}

    name: Update Terraform Docs and Dependencies
    runs-on: ubuntu-latest
    needs: terraform-init
    
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Terraform Format
        id: update_format
        shell: bash
        run: terraform fmt -recursive -diff

      - name: Run Terraform-Docs && Push Changes
        id: update_docs_push_changes
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: .terraform-docs.yml
          working-dir: .
          git-push: true
          git-commit-message: "[AUTO] UPDATE README && FIX formatting && UPDATE HCL Lock"
          git-push-sign-off: true
          fail-on-diff: false
          
  terraform-docs-deps-check:
    if: ${{ always() || needs.terraform-docs-deps-update.result == 'skipped' }}
  
    name: Check Terraform Docs and Dependencies
    runs-on: ubuntu-latest
    needs: ['terraform-init', 'terraform-docs-deps-update']
    
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check Terraform Formatting
        id: check_format
        run: terraform fmt -recursive -diff -check -write=false
        continue-on-error: true

      - name: Run Terraform Validate
        id: check_validate
        run: terraform validate
        continue-on-error: true
        
      - name: Check Docs
        id: check_docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: .terraform-docs.yml
          working-dir: .
          git-push: false
          fail-on-diff: true
        continue-on-error: true
        
      - name: Check if Lockfile Changed
        id: check_lockfile
        shell: bash
        run: |
          if git diff --exit-code .terraform.lock.hcl >/dev/null ; then
            echo "upgrade_used=false" >> $GITHUB_OUTPUT
            echo "No changes detected in the lockfile."
            exit 0
          else
            echo "upgrade_used=true" >> $GITHUB_OUTPUT
            echo "Providers were upgraded."
            exit 1
          fi
        continue-on-error: true
