---
name: Terraform Docs Deps Update

on: ['workflow_call']

permissions:
  contents: write

jobs:
  terraform-docs-deps-update:
    if: ${{ github.event_name == 'push' && github.ref_name != github.event.repository.default_branch }}

    name: Update Terraform Docs and Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Terraform Modules
        id: cache_modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-terraform-${{ github.sha }}

      - name: Terraform Format
        id: update_format
        shell: bash
        run: terraform fmt -recursive -diff

      - name: Run Terraform-Docs && Push Changes
        id: update_docs_push_changes
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: ".terraform-docs.yml"
          git-push: true
          git-commit-message: "[AUTO] UPDATE README && FIX formatting && UPDATE HCL Lock"
          git-push-sign-off: true
          fail-on-diff: false
          output-format: ""
          output-method: "replace"
          output-file: "README.md"
          template: ""
