---
name: Check/Update Docs, Formatting and Dependencies

on: ['push']

permissions: 
  contents: write
  
jobs:
  terraform-init:
    runs-on: ubuntu-latest
    
    steps:       
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Terraform Init
        run:  terraform init -backend=false -input=false -upgrade
        
      - name: Cache Terraform Modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
    

  terraform-docs-deps-update:
    if: ${{ github.event_name == 'push' && github.ref_name != github.event.repository.default_branch }}

    name: Update Terraform Docs and Dependencies
    runs-on: ubuntu-latest
    needs: terraform-init
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: terraform-docs-gh-actions
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: .terraform-docs.yml
          working-dir: .
          git-push: true
          git-commit-message: "[AUTO] UPDATE README && FIX formatting && UPDATE HCL Lock"
          git-push-sign-off: true
