---
name: Terraform Update

on: ['push', 'workflow_call']

permissions:
  contents: write

if: ${{ github.event_name == 'push' && github.ref_name != github.event.repository.default_branch }}

jobs:
  terraform-init:
    uses: ./.github/workflows/terraform-init.yml

  terraform-docs-deps-update:
    uses: ./.github/workflows/terraform-docs-deps-update.yml
    needs: ['terraform-init']

  terraform-validation:
    uses: ./.github/workflows/terraform-validation.yml
    needs: ['terraform-init']
