---
name: Check/Update Docs, Formatting and Dependencies

on: ['push']

permissions: 
  contents: write
  
jobs:
  terraform-init:
    name: Terraform Init
    runs-on: ubuntu-latest
    
    steps:       
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Terraform Init
        id: terraform_init
        shell: bash
        run:  terraform init -backend=false -input=false -upgrade
        
      - name: Cache Terraform Modules
        id: cache_modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-terraform-${{ github.sha }}

  terraform-docs-deps-update:
    if: ${{ github.event_name == 'push' && github.ref_name != github.event.repository.default_branch }}

    name: Update Terraform Docs and Dependencies
    runs-on: ubuntu-latest
    needs: terraform-init
    
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Cache Terraform Modules
        id: cache_modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-terraform-${{ github.sha }}

      - name: Terraform Format
        id: update_format
        shell: bash
        run: terraform fmt -recursive -diff

      - name: Run Terraform-Docs && Push Changes
        id: update_docs_push_changes
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: .terraform-docs.yml
          working-dir: .
          git-push: true
          git-commit-message: "[AUTO] UPDATE README && FIX formatting && UPDATE HCL Lock"
          git-push-sign-off: true
          fail-on-diff: false
          
  terraform-format-check:
    if: ${{ always() }}
  
    name: Terraform Format
    runs-on: ubuntu-latest
    needs: ['terraform-init', 'terraform-docs-deps-update']
    
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check Terraform Formatting
        id: check_format
        run: terraform fmt -recursive -diff -check -write=false
        
  terraform-validate-check:
    if: ${{ always() }}
  
    name: Terraform Validate
    runs-on: ubuntu-latest
    needs: ['terraform-init', 'terraform-docs-deps-update']
    
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Cache Terraform Modules
        id: cache_modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            .terraform
          key: ${{ runner.os }}-terraform-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-terraform-${{ github.sha }}

      - name: Run Terraform Validate
        id: check_validate
        run: terraform validate
        
  terraform-docs-check:
    if: ${{ always() }}
  
    name: Docs Check
    runs-on: ubuntu-latest
    needs: ['terraform-init', 'terraform-docs-deps-update']
    
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Check Docs
        id: check_docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: .terraform-docs.yml
          working-dir: .
          git-push: false
          fail-on-diff: true
        
  terraform-lockfile-check:
    if: ${{ always() }}
  
    name: Lockfile Check
    runs-on: ubuntu-latest
    needs: ['terraform-init', 'terraform-docs-deps-update']
    
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Hash Original Lockfile
        id: hash_original_lockfile
        shell: bash
        run: |
          if [ -f .terraform.lock.hcl ]; then
            LOCKFILE_HASH=$(sha256sum .terraform.lock.hcl | awk '{ print $1 }')
            echo "original_lockfile_hash=$LOCKFILE_HASH" >> $GITHUB_OUTPUT
          else
            echo "original_lockfile_hash=" >> $GITHUB_OUTPUT
          fi
          
      - name: Cache Terraform Modules
        id: cache_modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            .terraform.lock.hcl
          key: ${{ runner.os }}-terraform-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-terraform-${{ github.sha }}
        
      - name: Check if Lockfile Changed
        id: check_lockfile
        shell: bash
        run: |
          if [ -f .terraform.lock.hcl ]; then
            NEW_LOCKFILE_HASH=$(sha256sum .terraform.lock.hcl | awk '{ print $1 }')
          else
            echo 'Lockfile has changed'
            exit 1
          fi
          if [ "${{ steps.hash_original_lockfile.outputs.original_lockfile_hash }}" == $NEW_LOCKFILE_HASH ]; then
            echo 'Lockfile has not changed'
            exit 0
          else
            echo 'Lockfile has changed'
            exit 1
          fi
