---
name: TF Init

on: 
  workflow_call:
  repository_dispatch:
    types: ['setup'] 

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  tf-init:
    name: TF Init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: TF Init
        id: tf_init_upgrade
        run:  terraform init -backend=false -input=false

      - name: Cache TF Modules
        id: cache_modules
        uses: actions/cache@v4.1.1
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-tf-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-tf-${{ github.run_id }}
