---
name: Update TF Lockfile

run-name: "#${{ github.event.client_payload.id }}: ${{ github.event.client_payload.ref }}"

on:
  workflow_call:
  repository_dispatch:
    types: ['updates']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  update-tf-lockfile:
    name: Update TF Lockfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.client_payload.ref }}

      - name: TF Init
        id: tf_init_upgrade_true
        run:  terraform init -backend=false -input=false -upgrade

      - name: Cache TF Modules
        id: cache_modules
        uses: actions/cache@v4.1.0
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-tf-${{ github.event.client_payload.id }}
          restore-keys: |
            ${{ runner.os }}-tf-${{ github.event.client_payload.id }}

      - name: Set up Git config
        id: git_config
        run: |
          git config --global user.name "tf-lockfile[bot]"
          git config --global user.email "tf-lockfile[bot]@users.noreply.github.com"

      - name: Commit and push changes
        id: git_commit_and_push
        run: |
          git add -A || true
          git commit -m "[AUTO] Update TF Lockfile" || true
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
