---
name: Update TF README

run-name: "#${{ github.event.client_payload.id }}: ${{ github.event.client_payload.ref }}"

on:
  workflow_call:
  repository_dispatch:
    types: ['updates']

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  update-tf-readme:
    name: Update TF README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.client_payload.ref }}

      - name: Cache TF Modules
        id: cache_modules
        uses: actions/cache@v4.1.2
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: ${{ runner.os }}-tf-${{ github.event.client_payload.id }}
          restore-keys: |
            ${{ runner.os }}-tf-${{ github.event.client_payload.id }}

      - name: Run TF Docs Update
        id: update_docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: ".terraform-docs.yml"
          git-push: false
          fail-on-diff: false
          output-format: ""
          output-method: "replace"
          output-file: "README.md"
          template: ""

      - name: Set up Git config
        id: git_config
        run: |
          git config --global user.name "tf-readme[bot]"
          git config --global user.email "tf-readme[bot]@users.noreply.github.com"

      - name: Commit and push changes
        id: git_commit_and_push
        run: |
          git add -A || true
          git commit -m "[AUTO] Update TF README" || true
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
